### ISSUE TITLE
Not functioning when a security key (e.g. Yubikey) is added to Keyhub.

### ISSUE THREAD

**Issue by lesteenman** [topicuskeyhub/aws-keyhub#18]
By adding such a security token, the Puppeteer flow breaks, as the headless Chromium instance will ask for confirmation by security key rather than verification token.

The error looks as follows:

```
aws-keyhub
Error: verification code field not found
    at askAndFillVerificationCodeIfFieldExists (/Users/eriksteenman/.nvm/versions/node/v15.14.0/lib/node_modules/aws-keyhub/src/login.js:150:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.login (/Users/eriksteenman/.nvm/versions/node/v15.14.0/lib/node_modules/aws-keyhub/src/login.js:68:17)
```

**Comment by lesteenman** [comment]
This could possibly be fixed by switching back to the verification key authentication mechanism if the `webauthn` mechanism is detected.

With this selector, we can detect the mechanism is active:

```
const webauthnDetectionSelector = '.webauthn--indicator'
```

And we can switch back to the verification code method with the following function:

```
async function switchToVerificationCodeMethod(page) {
    xpathSelector = "//a[contains(text(), 'Use a 2FA app')]"
    try {
        const [button] = await page.$x(xpathSelector)
        await button.click()
    } catch (error) {
        console.warn("failed to switch to verification key method.");
        throw error;
    }
}
```

But Chromium shows a popup that blocks clicks on the page:

![image](https://user-images.githubusercontent.com/963290/123261260-d1b0cb80-d4f6-11eb-8692-a09f4efa083f.png)

I have not yet found a way to detect or close this dialog through Puppeteer.

**Comment by lesteenman** [comment]
Disabling the security key while keeping the verification code 2fa active circumvents this issue.

**Comment by ChristianHersevoort** [comment]
This should work with aws-keyhubv2 now
